version: '2.4'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-jcr:latest
    container_name: artifactory
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - "./artifactory:/artifactory_extra_conf"
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8082/artifactory/api/system/ping"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 40s

  jenkins:
    depends_on:
      - artifactory
    container_name: jenkins_controller
    build: ./jenkins_controller
    ports:
      - 8880:8080
      - 50000:50000
    restart: always
    volumes:
      - ./jenkins_controller/casc.yml:/usr/share/jenkins/ref/casc.yml
  jenkins_agent:
    depends_on:
      - jenkins
    container_name: jenkins_agent
    build: ./jenkins_agent
    ports:
      - "2222:22"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5o/5oky1sPs6dSZjwzvAMsE7/mW/NvT/kN0OCT3UwCuWCU+ws6d4u3iQFL1VeYBhTM7ytUq4s9PXDshBfX2GorEu6vtm5fQWjiGxdWhPpWTk7aIygBhLJLJceQ8eAbNpdfbf9Pw05bB7YpskrsVzi0IH81SGNcwvmtpYm939Qg1jFRrz2BQA2dQ1GofxCSn2R4259+FgtzB6GSKx09noN9K469ddM+KsUMihnljgR1CkdM7XR8EizfAGbYwVQVPXMvwITf6nLYvGpLFsdweLVLdFtu+ZL8/38mfWQwCso4e7Fjx+bezRh4HzKAC8Fxg7H9DrSCX3oQTST9uYo6OheYVFGHTxwywXv75oezKglyQpYwm3xqtp9OGn7ec6Ec+5UnkO3CwUw+u93pnNmvmPxJstDcSOl58yRCG+HIbtpaSgfD52Vd3fPpcw2A2iGOD9WxvbUowdDTROHwgxFkuYoTmexgkoHcmpMmvuyWO1aaf7ttFOV3nL4rIxEoc8bbEU=
  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:9.2.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always

  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: always

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always
